### PR TITLE
Support for MACsec statistics

### PR DESCRIPTION
**Pull request by qbdwlr**
Build dependency on https://github.com/Azure/sonic-swss-common/pull/520

### CODE REVIEW

**Comment by kcudnik** [comment]
to pass  coverage.Azure.sonic-sairedis.amd64 you would need to add unittests at 50% for added code, can you also add unittests  for your code?

**Comment by qbdwlr** [comment]
> to pass coverage.Azure.sonic-sairedis.amd64 you would need to add unittests at 50% for added code, can you also add unittests for your code?

@kcudnik  Can you point me to similar unittests for sairedis FlexCounter support?

**Comment by kcudnik** [comment]
you can start adding tests in sonic-sairedis/unittest/syncd path, creating file TestFlexCounter.cpp and follow pattern like for other files in sonic-sairedis/unittest/*, you would just need to cover like 50% of code added of this PR to pass the tests, you probably need to get familiar with gtest framework

**Comment by qbdwlr** [comment]
@kcudnik @Pterosaur I am only assigned to work on SONiC PRs for another week, so I cannot undertake providing all new coverage infrastructure for sairedis FlexCounters in the context of this PR.  If coverage is now a requirement for sairedis PR approval, then Ze will have to take up that effort in a separate PR.

**Comment by kcudnik** [comment]
@qbdwlr ok, then i can force merge this after tests passes, skipping coverage but it needs to be added later

**Comment by qbdwlr** [comment]
@kcudnik All tests are now passing.  Could you merge this as agreed?

**Comment by qbdwlr** [comment]
@kcudnik After rebasing to include latest commits to sairedis, I see the following failures in lgtm.com that are unrelated to any changes I introduced.  Is this a known issue?
[2021-11-23 16:14:12] [build-stderr] saiaclschema_ut.cpp:1:10: fatal error: gmock/gmock.h: No such file or directory
[2021-11-23 16:14:12] [build-stderr]     1 | #include <gmock/gmock.h>
[2021-11-23 16:14:12] [build-stderr]       |          ^~~~~~~~~~~~~~~
[2021-11-23 16:14:12] [build-stderr] compilation terminated.

**Comment by kcudnik** [comment]
this is related to latest swss-common starting using gmock lib, it's attempted to be fixed here : https://github.com/Azure/sonic-sairedis/pull/968/commits/42e54276e89258aa53258462ce416fb4abf54f44

**Comment by qbdwlr** [comment]
@kcudnik @Pterosaur Can we get this PR approved/merged?  Or do we have to wait for someone to fix these flaky vstests?  I was able to re-use recently merged FlexCounter unittest infra to get >50% coverage for this PR, so that is no longer an issue.

**Review by kcudnik — APPROVED** [review]

**Review by Pterosaur — APPROVED** [review]

**Comment by qbdwlr** [comment]
@kcudnik This PR is approved but hasn't been merged yet because vstests have been broken for two weeks.  I don't see any fixes for vstest happening soon.  Can this PR be merged despite the vstest failures?

**Comment by kcudnik** [comment]
ok
